---
title: "12.01"
output: html_notebook
---


```{r setup}
library(readxl)
library(stringr)
library(tidyverse)
```


```{r import}
input <- read.table("input1201.txt")
```


```{r part1}
inputnum <- input %>%
  mutate(num = sapply(str_extract_all(V1, "[0-9]+"), paste, collapse = ""),
         numfin = gsub(" ", "", paste(substr(num, 1, 1), substr(num, str_length(num), str_length(num)))))

sum(as.numeric(inputnum$numfin))
```

```{r part2}

inputnum <- input %>%
  mutate(num = str_replace_all(V1, c("twone" = "21", "threeight" = "38", "eighthree" = "83", "oneight" = "18", "eightwo" = "82", "fiveight" ="58", "sevenine" ="79", "nineight" = "98", "one" = "1", "two" = "2", "three" = "3",  "four" = "4", "five" = "5", "six" = "6", "seven" = "7",  "eight" = "8",  "nine" = "9")),
         numnum = sapply(str_extract_all(num, "[0-9]+"), paste, collapse = ""),
         numfin = gsub(" ", "", paste(substr(numnum, 1, 1), substr(numnum, str_length(numnum), str_length(numnum)))))

sum(as.numeric(inputnum$numfin))
```

